### ISSUE TITLE
Seg-Fault in certain cases

### ISSUE THREAD

**Issue by nishaq503** [PolusAI/filepattern#19]
I’m getting a seg-fault with the following setup:

* A directory containing files with the following names: 
  - `img_x(1-10)_c1_darkfield.ome.tif`
  - `img_x(1-10)_c1_flatfield.ome.tif`
  - `img_x(1-10)_c2_darkfield.ome.tif`
  - `img_x(1-10)_c2_flatfield.ome.tif`
  - `img_x(1-10)_c3_darkfield.ome.tif`
  - `img_x(1-10)_c3_flatfield.ome.tif`
  - `img_x(1-10)_c4_darkfield.ome.tif`
  - `img_x(1-10)_c4_flatfield.ome.tif`

* The pattern: `"img_x(1-10)_c{c:d}_flatfield.ome.tif"`

And the following python code:

```python
ff_fp = FilePattern(str(ff_dir), ff_pattern)
ff_variables = ff_fp.get_variables()
logger.info(f"Flatfield variables: {ff_variables}")

for group, files in ff_fp(group_by=ff_variables):
    logger.info(f"Flatfield group: {group}")
    logger.info(f"Flatfield names: {[p.name for _, [p] in files]}")
```

The variables are correctly identified as `["c"]` and the seg-fault happens in the `for ...` statement starting the loop.

The error message is uninformative, simply saying that a seg-fault occurred.

**Comment by sameeul** [comment]
Fixed in v2.0.1
