### ISSUE TITLE
incorrect inferred file-pattern

### ISSUE THREAD

**Issue by gauharbains** [PolusAI/filepattern#2]
There seems to be a bug in the `infer_pattern` function that is causing an error in the following workflow:
http://wipp-ui.ci.aws.labshare.org/workflows/detail/60e8ae2552091f3ee8e92bcb

The input image collection is:
http://wipp-ui.ci.aws.labshare.org/images-collections/5e94794b229ba30007a9eb13

It infers the following pattern `r00{r}_z000_y{t+}_x0{cc}_c{z+}0{y+}.ome.tif` which is incorrect.

**Comment by Priyaaxle** [comment]
I am also facing issues with inferred file pattern.
Workflow:  http://wipp-ui.test.aws.labshare.org/workflows/detail/60f6b117d18208654f654289
Image collection: http://wipp-ui.test.aws.labshare.org/images-collections/5f8f584637c1120008aa7960
