### ISSUE TITLE
Adding support to capture groups with custom types

### ISSUE THREAD

**Issue by hamshkhawar** [PolusAI/filepattern#29]
At the moment filePattern2 has support for parsing directories (if specified using digits or characters) and fails when it contains both, whitespaces and metacharacter. So It would be better to add a support to capture groups with custom types as the folder names may be defined in various ways. Following below is an example of folder names of one of the dataset

├── 190725-3-36-HSV-1A_Plate_13965
├── 190725-3-36-HSV-1B_Plate_13966
├── 190725-3-36-HSV-1C_Plate_13967
├── 190725-3-36-HSV-1D_Plate_13969
├── 190801-3-37-HSV-2A_Plate_13992
├── 190801-3-37-HSV-2B_Plate_13993
├── 190801-3-37-HSV-2C_Plate_13994
├── 190801-3-37-HSV-2D_Plate_13995
├── 190808-3-38-HSV-3A_Plate_14024
├── 190808-3-38-HSV-3B_Plate_14025
├── 190808-3-38-HSV-3C_Plate_14026
└── 190808-3-38-HSV-3D_Plate_14027

**Comment by sameeul** [comment]
Fixed in v2.0.3
